# Generated by Django 4.0.5 on 2022-07-12 14:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auctioncategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionbid',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 7, 12, 14, 6, 19, 360853, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
